# src/pipelines/training_ppln.py

"""
Model training pipeline for the phishing email classifier.

This module is responsible for:
    1. Loading persisted training and validation features.
    2. Loading the corresponding target labels.
    3. Training a Logistic Regression classifier.
    4. Evaluating the trained model on the validation dataset.
    5. Persisting the trained classifier.
    6. Returning a standardized PipelineResult.

The test dataset is deliberately not used during this pipeline.
Final test evaluation will be handled separately.
"""

import logging
from pathlib import Path
from typing import Any

import joblib
import numpy as np
from scipy.sparse import load_npz
from sklearn.base import ClassifierMixin
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
)
from src.models.model_factory import ModelFactory
from src.orchestration.base_ppln import BasePipeline, PipelineResult


class TrainingPipeline(BasePipeline):
    """
    Pipeline responsible for training the phishing email classifier.

    The model is trained using TF-IDF features generated by the
    FeaturePipeline.
    """

    PIPELINE_NAME = "training"

    def __init__(
        self,
        features_dir: str | Path,
        model_output_path: str | Path,
        random_state: int = 42,
        model_name: str = "logistic_regression",
    ) -> None:
        """
        Initialize the training pipeline.

        Args:
            features_dir: Directory containing persisted feature matrices
                and labels.
            model_output_path: Path where the trained model will be saved.
            random_state: Random seed used by the classifier.

        Raises:
            TypeError: If arguments have invalid types.
            ValueError: If paths are empty or random_state is invalid.
        """

        self.logger = logging.getLogger(self.__class__.__name__)

        if not isinstance(features_dir, (str, Path)):
            raise TypeError("features_dir must be a string or Path.")

        if not isinstance(model_output_path, (str, Path)):
            raise TypeError(
                "model_output_path must be a string or Path."
            )

        if not isinstance(random_state, int):
            raise TypeError("random_state must be an integer.")

        self.features_dir = Path(features_dir)
        self.model_output_path = Path(model_output_path)
        self.random_state = random_state
        self.model_name = model_name
        self.model_factory = ModelFactory()

    @property
    def name(self) -> str:
        """
        Return the registered pipeline name.

        Returns:
            str: Pipeline identifier.
        """

        return self.PIPELINE_NAME

    def _validate_feature_files(self) -> None:
        """
        Verify that the required training and validation artifacts exist.

        Raises:
            FileNotFoundError: If any required artifact is missing.
            ValueError: If the feature directory is not a directory.
        """

        if not self.features_dir.exists():
            raise FileNotFoundError(
                f"Feature directory not found: {self.features_dir}"
            )

        if not self.features_dir.is_dir():
            raise ValueError(
                f"Feature path is not a directory: {self.features_dir}"
            )

        required_files = [
            "X_train.npz",
            "X_validation.npz",
            "y_train.joblib",
            "y_validation.joblib",
        ]

        missing_files = [
            filename
            for filename in required_files
            if not (self.features_dir / filename).exists()
        ]

        if missing_files:
            raise FileNotFoundError(
                "Required training artifacts are missing: "
                f"{missing_files}"
            )

    def _load_training_data(
        self,
    ) -> tuple[Any, np.ndarray, Any, np.ndarray]:
        """
        Load training and validation features and labels.

        Returns:
            Tuple containing:
                training_features,
                training_labels,
                validation_features,
                validation_labels.
        """

        training_features = load_npz(
            self.features_dir / "X_train.npz"
        )

        validation_features = load_npz(
            self.features_dir / "X_validation.npz"
        )

        training_labels = np.asarray(
            joblib.load(
                self.features_dir / "y_train.joblib"
            )
        )

        validation_labels = np.asarray(
            joblib.load(
                self.features_dir / "y_validation.joblib"
            )
        )

        self.logger.info(
            "Training features loaded: %s",
            training_features.shape,
        )

        self.logger.info(
            "Validation features loaded: %s",
            validation_features.shape,
        )

        return (
            training_features,
            training_labels,
            validation_features,
            validation_labels,
        )

    @staticmethod
    def _validate_data(
        training_features: Any,
        training_labels: np.ndarray,
        validation_features: Any,
        validation_labels: np.ndarray,
    ) -> None:
        """
        Validate feature and label dimensions.

        Args:
            training_features: Training feature matrix.
            training_labels: Training target labels.
            validation_features: Validation feature matrix.
            validation_labels: Validation target labels.

        Raises:
            ValueError: If feature and label dimensions do not match.
        """

        if training_features.shape[0] != len(training_labels):
            raise ValueError(
                "Training feature rows do not match training labels."
            )

        if validation_features.shape[0] != len(validation_labels):
            raise ValueError(
                "Validation feature rows do not match validation labels."
            )

        if training_features.shape[1] != validation_features.shape[1]:
            raise ValueError(
                "Training and validation feature counts do not match."
            )

        if len(np.unique(training_labels)) < 2:
            raise ValueError(
                "Training data must contain at least two classes."
            )

    def _build_model(self) -> ClassifierMixin:
        """
        Create the configured classification model through ModelFactory.

        Returns:
            ClassifierMixin: An initialized classification model.
        """

        return self.model_factory.create_model(
            model_name=self.model_name,
            model_parameters={
                "max_iter": 1000,
                "random_state": self.random_state,
                "class_weight": "balanced",
            },
        )
    
    def _evaluate(
        self,
        model: ClassifierMixin,
        validation_features: Any,
        validation_labels: np.ndarray,
    ) -> dict[str, float]:
        """
        Evaluate the trained model on validation data.

        Args:
            model: Trained classification model.
            validation_features: Validation feature matrix.
            validation_labels: Validation target labels.

        Returns:
            Dictionary containing validation metrics.
        """

        predictions = model.predict(validation_features)

        metrics = {
            "accuracy": float(
                accuracy_score(validation_labels, predictions)
            ),
            "precision": float(
                precision_score(
                    validation_labels,
                    predictions,
                    zero_division=0,
                )
            ),
            "recall": float(
                recall_score(
                    validation_labels,
                    predictions,
                    zero_division=0,
                )
            ),
            "f1_score": float(
                f1_score(
                    validation_labels,
                    predictions,
                    zero_division=0,
                )
            ),
        }

        self.logger.info(
            "Validation metrics | accuracy=%.4f | precision=%.4f | "
            "recall=%.4f | f1=%.4f",
            metrics["accuracy"],
            metrics["precision"],
            metrics["recall"],
            metrics["f1_score"],
        )

        return metrics

    def _save_model(self, model: ClassifierMixin) -> None:
        """
        Persist the trained classifier.

        Args:
            model: Trained classifier.
        """

        self.model_output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        joblib.dump(
            model,
            self.model_output_path,
        )

        self.logger.info(
            "Trained model saved to: %s",
            self.model_output_path,
        )

    def run(self) -> PipelineResult:
        """
        Execute the model training workflow.

        Returns:
            PipelineResult: Standardized result describing pipeline execution.

        Raises:
            RuntimeError: If model training fails.
        """

        self.logger.info("Starting model training pipeline.")

        self._validate_feature_files()

        (
            training_features,
            training_labels,
            validation_features,
            validation_labels,
        ) = self._load_training_data()

        self._validate_data(
            training_features=training_features,
            training_labels=training_labels,
            validation_features=validation_features,
            validation_labels=validation_labels,
        )

        model = self._build_model()

        self.logger.info(
            "Training '%s' model on %d samples with %d features.",
            self.model_name,
            training_features.shape[0],
            training_features.shape[1],
)

        model.fit(
            training_features,
            training_labels,
        )

        self.logger.info(
            "Model training completed successfully."
        )

        validation_metrics = self._evaluate(
            model=model,
            validation_features=validation_features,
            validation_labels=validation_labels,
        )

        self._save_model(model)

        return PipelineResult(
            pipeline_name=self.name,
            success=True,
            message="Model training completed successfully.",
            metadata={
                "model_type": self.model_name,
                "model_path": str(self.model_output_path),
                "training_rows": int(training_features.shape[0]),
                "validation_rows": int(validation_features.shape[0]),
                "feature_count": int(training_features.shape[1]),
                "validation_metrics": validation_metrics,
            },
        )