# src/pipelines/training_ppln.py

"""
Model training pipeline for the phishing email classifier.

This module is responsible for:
    1. Loading persisted training and validation features.
    2. Loading the corresponding target labels.
    3. Creating the configured classification model.
    4. Training the selected classifier.
    5. Evaluating the trained model on the validation dataset.
    6. Persisting the trained classifier.
    7. Returning a standardized PipelineResult.

The test dataset is deliberately not used during this pipeline.
Final test evaluation will be handled separately.
"""

import logging
from pathlib import Path
from typing import Any
import time

import joblib
import numpy as np
from scipy.sparse import load_npz
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
)

from src.models.model_factory import Classifier, ModelFactory
from src.orchestration.base_ppln import BasePipeline, PipelineResult
from src.tracking.mlflow_tracker import MLflowTracker


class TrainingPipeline(BasePipeline):
    """
    Pipeline responsible for training the phishing email classifier.

    The model is trained using TF-IDF features generated by the
    FeaturePipeline.
    """

    PIPELINE_NAME = "training"

    def __init__(
        self,
        features_dir: str | Path,
        model_output_path: str | Path,
        random_state: int = 42,
        model_name: str = "logistic_regression",
        model_parameters: dict[str, Any] | None = None,
        mlflow_config: dict[str, Any] | None = None,
        register_model: bool = False,
    ) -> None:
        """
        Initialize the training pipeline.

        Args:
            features_dir: Directory containing persisted feature matrices
                and labels.
            model_output_path: Path where the trained model will be saved.
            random_state: Random seed used by the classifier.
            model_name: Name of the classification model to train.
            model_parameters: Model-specific hyperparameters loaded from
                the external configuration.

        Raises:
            TypeError: If arguments have invalid types.
            ValueError: If paths are empty, random_state is invalid,
                or model_parameters are invalid.
        """

        self.logger = logging.getLogger(self.__class__.__name__)

        if not isinstance(features_dir, (str, Path)):
            raise TypeError("features_dir must be a string or Path.")

        if not isinstance(model_output_path, (str, Path)):
            raise TypeError(
                "model_output_path must be a string or Path."
            )

        if not isinstance(random_state, int):
            raise TypeError("random_state must be an integer.")

        if not isinstance(model_name, str) or not model_name.strip():
            raise ValueError(
                "model_name must be a non-empty string."
            )

        if model_parameters is not None and not isinstance(
            model_parameters,
            dict,
        ):
            raise TypeError(
                "model_parameters must be a dictionary."
            )

        if mlflow_config is not None and not isinstance(
            mlflow_config,
            dict,
        ):
            raise TypeError(
                "mlflow_config must be a dictionary."
            )

        
        self.features_dir = Path(features_dir)
        self.model_output_path = Path(model_output_path)
        self.random_state = random_state
        self.model_name = model_name
        self.model_parameters = model_parameters or {}
        self.model_factory = ModelFactory()
        self.mlflow_config = mlflow_config or {}
        self.register_model = register_model
        self.mlflow_tracker: MLflowTracker | None = None
        self.mlflow_run_id: str | None = None
        self.mlflow_model_version: str | None = None

        if self.mlflow_config.get("enabled", False):

            self.mlflow_tracker = MLflowTracker(
            experiment_name=self.mlflow_config["experiment_name"],
            tracking_uri=self.mlflow_config.get("tracking_uri"),
        )

    @property
    def name(self) -> str:
        """
        Return the registered pipeline name.

        Returns:
            str: Pipeline identifier.
        """

        return self.PIPELINE_NAME

    def _validate_feature_files(self) -> None:
        """
        Verify that the required training and validation artifacts exist.

        Raises:
            FileNotFoundError: If any required artifact is missing.
            ValueError: If the feature directory is not a directory.
        """

        if not self.features_dir.exists():
            raise FileNotFoundError(
                f"Feature directory not found: {self.features_dir}"
            )

        if not self.features_dir.is_dir():
            raise ValueError(
                f"Feature path is not a directory: {self.features_dir}"
            )

        required_files = [
            "X_train.npz",
            "X_validation.npz",
            "y_train.joblib",
            "y_validation.joblib",
        ]

        missing_files = [
            filename
            for filename in required_files
            if not (self.features_dir / filename).exists()
        ]

        if missing_files:
            raise FileNotFoundError(
                "Required training artifacts are missing: "
                f"{missing_files}"
            )

    def _load_training_data(
        self,
    ) -> tuple[Any, np.ndarray, Any, np.ndarray]:
        """
        Load training and validation features and labels.

        Returns:
            Tuple containing:
                training_features,
                training_labels,
                validation_features,
                validation_labels.
        """

        training_features = load_npz(
            self.features_dir / "X_train.npz"
        )

        validation_features = load_npz(
            self.features_dir / "X_validation.npz"
        )

        training_labels = np.asarray(
            joblib.load(
                self.features_dir / "y_train.joblib"
            )
        )

        validation_labels = np.asarray(
            joblib.load(
                self.features_dir / "y_validation.joblib"
            )
        )

        self.logger.info(
            "Training features loaded: %s",
            training_features.shape,
        )

        self.logger.info(
            "Validation features loaded: %s",
            validation_features.shape,
        )

        return (
            training_features,
            training_labels,
            validation_features,
            validation_labels,
        )

    @staticmethod
    def _validate_data(
        training_features: Any,
        training_labels: np.ndarray,
        validation_features: Any,
        validation_labels: np.ndarray,
    ) -> None:
        """
        Validate feature and label dimensions.

        Args:
            training_features: Training feature matrix.
            training_labels: Training target labels.
            validation_features: Validation feature matrix.
            validation_labels: Validation target labels.

        Raises:
            ValueError: If feature and label dimensions do not match.
        """

        if training_features.shape[0] != len(training_labels):
            raise ValueError(
                "Training feature rows do not match training labels."
            )

        if validation_features.shape[0] != len(validation_labels):
            raise ValueError(
                "Validation feature rows do not match validation labels."
            )

        if training_features.shape[1] != validation_features.shape[1]:
            raise ValueError(
                "Training and validation feature counts do not match."
            )

        if len(np.unique(training_labels)) < 2:
            raise ValueError(
                "Training data must contain at least two classes."
            )

    def _build_model(self) -> Classifier:
        """
        Create the configured classification model through ModelFactory.

        Model-specific hyperparameters are supplied externally through
        the configuration rather than being hardcoded in this pipeline.

        Returns:
            Classifier: An initialized classification model.
        """

        model_parameters = dict(self.model_parameters)

        model_parameters["random_state"] = self.random_state

        self.logger.info(
            "Creating '%s' model with configured parameters: %s",
            self.model_name,
            model_parameters,
        )

        return self.model_factory.create_model(
            model_name=self.model_name,
            model_parameters=model_parameters,
        )

    def _evaluate(
        self,
        model: Classifier,
        validation_features: Any,
        validation_labels: np.ndarray,
    ) -> dict[str, float]:
        """
        Evaluate the trained model on validation data.

        Args:
            model: Trained classification model.
            validation_features: Validation feature matrix.
            validation_labels: Validation target labels.

        Returns:
            Dictionary containing validation metrics.
        """

        predictions = model.predict(validation_features)

        metrics = {
            "accuracy": float(
                accuracy_score(validation_labels, predictions)
            ),
            "precision": float(
                precision_score(
                    validation_labels,
                    predictions,
                    zero_division=0,
                )
            ),
            "recall": float(
                recall_score(
                    validation_labels,
                    predictions,
                    zero_division=0,
                )
            ),
            "f1_score": float(
                f1_score(
                    validation_labels,
                    predictions,
                    zero_division=0,
                )
            ),
        }

        self.logger.info(
            "Validation metrics | accuracy=%.4f | precision=%.4f | "
            "recall=%.4f | f1=%.4f",
            metrics["accuracy"],
            metrics["precision"],
            metrics["recall"],
            metrics["f1_score"],
        )

        return metrics

    def _save_model(self, model: Classifier) -> None:
        """
        Persist the trained classifier.

        Args:
            model: Trained classifier.
        """

        self.model_output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        joblib.dump(
            model,
            self.model_output_path,
        )

        self.logger.info(
            "Trained model saved to: %s",
            self.model_output_path,
        )

    def run(self) -> PipelineResult:
        """
        Execute the model training workflow.

        Returns:
            PipelineResult: Standardized result describing pipeline execution.

        Raises:
            RuntimeError: If model training fails.
        """

        self.logger.info("Starting model training pipeline.")

        run_started = False
        run_status = "FINISHED"
        run_start_time = time.perf_counter()

        try:
            # --------------------------------------------------------
            # MLflow: Start a new tracking run.
            # --------------------------------------------------------

            if self.mlflow_tracker is not None:
                active_run = self.mlflow_tracker.start_run(
                    run_name=self.model_name
                )

                self.mlflow_run_id = active_run.info.run_id
                run_started = True

                self.mlflow_tracker.log_parameters(
                    {
                        "model_name": self.model_name,
                        "random_state": self.random_state,
                        **self.model_parameters,
                    }
                )

                self.mlflow_tracker.set_tags(
                    {
                        "pipeline": self.name,
                        "model": self.model_name,
                    }
                )

            self._validate_feature_files()
            (
                training_features,
                training_labels,
                validation_features,
                validation_labels,
            ) = self._load_training_data()

            self._validate_data(
                training_features=training_features,
                training_labels=training_labels,
                validation_features=validation_features,
                validation_labels=validation_labels,
            )

            model = self._build_model()

            self.logger.info(
                "Training '%s' model on %d samples with %d features.",
                self.model_name,
                training_features.shape[0],
                training_features.shape[1],
            )

            model.fit(
                training_features,
                training_labels,
            )

            self.logger.info(
                "Model training completed successfully."
            )

            validation_metrics = self._evaluate(
                model=model,
                validation_features=validation_features,
                validation_labels=validation_labels,
            )

            # --------------------------------------------------------
            # MLflow: Log validation metrics.
            # --------------------------------------------------------

            if self.mlflow_tracker is not None:
                self.mlflow_tracker.log_metrics(
                    {
                        "validation_accuracy": validation_metrics["accuracy"],
                        "validation_precision": validation_metrics["precision"],
                        "validation_recall": validation_metrics["recall"],
                        "validation_f1_score": validation_metrics["f1_score"],
                    }
                )

            self._save_model(model)

            # --------------------------------------------------------
            # MLflow: Log the trained model as an artifact.
            # --------------------------------------------------------

            if self.mlflow_tracker is not None:
                self.mlflow_tracker.log_artifact(
                    self.model_output_path,
                )

                # ----------------------------------------------------
                # MLflow: Register the underlying scikit-learn model.
                # ----------------------------------------------------

                if self.register_model:
                    registered_model_name = self.mlflow_config.get(
                        "registered_model_name"
                    )

                    if not registered_model_name:
                        raise ValueError(
                            "MLflow registered_model_name must be configured "
                            "when register_model=True."
                        )

                    self.mlflow_model_version = (
                        self.mlflow_tracker.log_and_register_model(
                            model=model.model,
                            registered_model_name=registered_model_name,
                        )
                    )
                    
            return PipelineResult(
                pipeline_name=self.name,
                success=True,
                message="Model training completed successfully.",
                metadata={
                    "model_type": self.model_name,
                    "model_path": str(self.model_output_path),
                    "training_rows": int(training_features.shape[0]),
                    "validation_rows": int(validation_features.shape[0]),
                    "feature_count": int(training_features.shape[1]),
                    "validation_metrics": validation_metrics,
                    "mlflow_run_id": self.mlflow_run_id,
                    "mlflow_model_version": self.mlflow_model_version,
                },
            )

        except Exception:
            run_status = "FAILED"
            self.logger.exception(
                "Model training pipeline failed."
            )
            raise

        # --------------------------------------------------------
        # MLflow: Always close the active run.
        # --------------------------------------------------------
        finally:
            if run_started and self.mlflow_tracker is not None:
                run_duration = time.perf_counter() - run_start_time

                self.mlflow_tracker.log_metrics(
                    {
                        "run_duration_seconds": run_duration,
                    }
                )

                self.mlflow_tracker.end_run(
                    status=run_status
                )